version: '2'

services:
  mongodb:
    image: mongo:3.2
    # TODO: mongod --smallfiles?
    command: mongod
    ports:
      - 27017:27017
    volumes:
      - ../archivist-api/db/mongo:/data

  api:
    depends_on:
      - mongodb
    build: ../archivist-api/
    ports:
      - 3000:3000
    environment:
      - DOCKERIZED=true
      - RAILS_ENV=development
    volumes:
      - /archivist-api/tmp
      - /tmp
      - ../archivist-api:/archivist-api

  web:
    depends_on:
      - api
    build: ../archivist-web/
    ports:
      - 8080:8080
    volumes:
      - ../archivist-web:/archivist-web
      - /archivist-web/node_modules
